# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-09-28 10:17
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sanitation', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Toilet',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('account_number', models.CharField(max_length=100)),
                ('toilet_tag', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(blank=True, max_length=65)),
                ('last_name', models.CharField(blank=True, max_length=65)),
                ('phone_number', models.IntegerField(blank=True, default=0)),
                ('user_id_number', models.IntegerField(blank=True, default=0)),
                ('location', models.CharField(blank=True, max_length=65)),
            ],
        ),
        migrations.AddField(
            model_name='toilet',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sanitation.User'),
        ),
    ]
