# Generated by Django 2.2.5 on 2019-10-03 06:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sanitation', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='mpesacallbacks',
            name='checkout_request_id',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='mpesacallbacks',
            name='merchant_id',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='mpesacalls',
            name='checkout_request_id',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='mpesacalls',
            name='merchant_id',
            field=models.TextField(default=''),
        ),
    ]
