# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-10-03 16:05
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sanitation', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bills',
            name='date',
        ),
        migrations.RemoveField(
            model_name='bills',
            name='toilet_tag',
        ),
    ]
