# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-09-28 16:23
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sanitation', '0002_auto_20190928_1317'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='account',
            field=models.CharField(blank=True, max_length=65),
        ),
    ]
